if(NOT BUILD_GAME_LIBRARIES AND NOT BUILD_GAME_QVMS)
    return()
endif()

include(utils/qvm_tools)
include(utils/set_output_dirs)

set(BASEQZ "baseqz")
set(BASEQZ_VERSION 305)

set(BASEQZ_CGAME_SOURCES
    ${SOURCE_DIR}/cgame/cg_scoreboard_ql.c
)

set(CGAME_SOURCES_BASEQZ ${CGAME_SOURCES} ${MPCGAME_SOURCES} ${BASEQZ_CGAME_SOURCES} ${GAME_MODULE_SHARED_SOURCES})
set(GAME_SOURCES_BASEQZ ${GAME_SOURCES} ${GAME_MODULE_SHARED_SOURCES})
set(UI_SOURCES_BASEQZ ${MPUI_SOURCES} ${GAME_MODULE_SHARED_SOURCES})

if(BUILD_GAME_LIBRARIES)
    set(CGAME_MODULE_BINARY_BASEQZ ${CGAME_MODULE_BINARY}_${BASEQZ})
    set(GAME_MODULE_BINARY_BASEQZ ${GAME_MODULE_BINARY}_${BASEQZ})
    set(UI_MODULE_BINARY_BASEQZ ${UI_MODULE_BINARY}_${BASEQZ})

if(BUILD_BASEQZ)
    add_library(                ${CGAME_MODULE_BINARY_BASEQZ} SHARED ${CGAME_SOURCES_BASEQZ} ${CGAME_BINARY_SOURCES})
    target_compile_definitions( ${CGAME_MODULE_BINARY_BASEQZ} PRIVATE CGAME MISSIONPACK BASEQZ=${BASEQZ_VERSION})
    target_link_libraries(      ${CGAME_MODULE_BINARY_BASEQZ} PRIVATE ${COMMON_LIBRARIES})
    set_target_properties(      ${CGAME_MODULE_BINARY_BASEQZ} PROPERTIES OUTPUT_NAME ${CGAME_MODULE_BINARY})
    set_output_dirs(            ${CGAME_MODULE_BINARY_BASEQZ} SUBDIRECTORY ${BASEQZ})
    install(TARGETS             ${CGAME_MODULE_BINARY_BASEQZ} LIBRARY DESTINATION ${BASEQZ})

    add_library(                ${GAME_MODULE_BINARY_BASEQZ} SHARED ${GAME_SOURCES_BASEQZ} ${GAME_BINARY_SOURCES})
    target_compile_definitions( ${GAME_MODULE_BINARY_BASEQZ} PRIVATE QAGAME MISSIONPACK BASEQZ=${BASEQZ_VERSION})
    target_link_libraries(      ${GAME_MODULE_BINARY_BASEQZ} PRIVATE ${COMMON_LIBRARIES})
    set_target_properties(      ${GAME_MODULE_BINARY_BASEQZ} PROPERTIES OUTPUT_NAME ${GAME_MODULE_BINARY})
    set_output_dirs(            ${GAME_MODULE_BINARY_BASEQZ} SUBDIRECTORY ${BASEQZ})
    install(TARGETS             ${GAME_MODULE_BINARY_BASEQZ} LIBRARY DESTINATION ${BASEQZ})

    add_library(                ${UI_MODULE_BINARY_BASEQZ} SHARED ${UI_SOURCES_BASEQZ} ${UI_BINARY_SOURCES})
    target_compile_definitions( ${UI_MODULE_BINARY_BASEQZ} PRIVATE UI MISSIONPACK BASEQZ=${BASEQZ_VERSION})
    target_link_libraries(      ${UI_MODULE_BINARY_BASEQZ} PRIVATE ${COMMON_LIBRARIES})
    set_target_properties(      ${UI_MODULE_BINARY_BASEQZ} PROPERTIES OUTPUT_NAME ${UI_MODULE_BINARY})
    set_output_dirs(            ${UI_MODULE_BINARY_BASEQZ} SUBDIRECTORY ${BASEQZ})
    install(TARGETS             ${UI_MODULE_BINARY_BASEQZ} LIBRARY DESTINATION ${BASEQZ})
endif()

endif()

if(BUILD_GAME_QVMS)
    set(CGAME_MODULE_QVM_BASEQZ ${CGAME_MODULE}qvm_${BASEQZ})
    set(GAME_MODULE_QVM_BASEQZ ${GAME_MODULE}qvm_${BASEQZ})
    set(UI_MODULE_QVM_BASEQZ ${UI_MODULE}qvm_${BASEQZ})

if(BUILD_BASEQZ)
    add_qvm(${CGAME_MODULE_QVM_BASEQZ}
        DEFINITIONS CGAME MISSIONPACK BASEQZ=${BASEQZ_VERSION}
        OUTPUT_NAME ${CGAME_MODULE}
        OUTPUT_DIRECTORY ${BASEQZ}/vm
        SOURCES ${CGAME_SOURCES_BASEQZ} ${CGAME_QVM_SOURCES})

    add_qvm(${GAME_MODULE_QVM_BASEQZ}
        DEFINITIONS QAGAME MISSIONPACK BASEQZ=${BASEQZ_VERSION}
        OUTPUT_NAME ${GAME_MODULE}
        OUTPUT_DIRECTORY ${BASEQZ}/vm
        SOURCES ${GAME_SOURCES_BASEQZ} ${GAME_QVM_SOURCES})

    add_qvm(${UI_MODULE_QVM_BASEQZ}
        DEFINITIONS UI MISSIONPACK BASEQZ=${BASEQZ_VERSION}
        OUTPUT_NAME ${UI_MODULE}
        OUTPUT_DIRECTORY ${BASEQZ}/vm
        SOURCES ${UI_SOURCES_BASEQZ} ${UI_QVM_SOURCES})
endif()

endif()
